export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const CLEAR_COMPLETED_TODO = "CLEAR_COMPLETED_TODO"
export const RESET_TODO = "RESET_TODO"
export const FILTER_TODO = "FILTER_TODO"
